services:
  front:
    build: ./front
    ports:
      - "8080:3000"
    volumes:
      - "./front:/usr/src/app/front"

  back:
    build: ./back
    ports:
      - "49161:8000"
    volumes:
      - "./back:/usr/src/app/back"
