name: test

on:
  push:
    branches:
      - "release"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd schoolmaterial2 && git pull && docker compose up -d --build --force-recreate"
